services:
  - type: web
    name: combat-ai-backend
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: COMBAT_AI_CORS_ALLOW_ORIGINS
        value: http://localhost:5173,https://mma-ai-five.vercel.app
      - key: YOUTUBE_COOKIES
        sync: false
